### ISSUE TITLE
2018-2023 Tesla Model 3 wrong class

### ISSUE THREAD

**Issue by bluestreakgp7** [Bjorn248/scca_classifier#299]
2018-2023 Tesla Model 3 should be in A Street for the Street Category, not Super Street like it was prior to the reclassification.

**Comment by Bjorn248** [comment]
Thanks for the report! I plan on fixing this tomorrow.

**Comment by Bjorn248** [comment]
@bluestreakgp7 this should be fixed!

**Comment by bluestreakgp7** [comment]
Hey there, unfortunately the Tesla Model 3 still shows up under Super Street. The Model Y is already under A Street.

![image](https://github.com/user-attachments/assets/80901b9d-e1a9-4f99-823a-8925f5aa54c7)

**Comment by Bjorn248** [comment]
> Hey there, unfortunately the Tesla Model 3 still shows up under Super Street. The Model Y is already under A Street.
> 
> ![image](https://github.com/user-attachments/assets/80901b9d-e1a9-4f99-823a-8925f5aa54c7)
> 

Have you tried a control + shift + r to refresh? Sometimes the browser caches the website so updates aren't immediately visible.

**Comment by bluestreakgp7** [comment]
I just tried that. Looks like it worked! Will keep that in mind for next time.
